[ADD] IsMask boolean to layer and fixed bug in navmeshAttribute
Rhinox-Training/rhinox-guiutils pull request #46
Opened 2023-06-09 12:48 UTC by GlennQuintyn

I tried to add the requested feature #44,  
while also fixing a bug in the LayerAttributeDrawer.

 ## ADD
[ADD] LayerUtils.GetLayerNames() to give all layernames that aren't null.

## MOD
[MOD] LayerAttribute to have IsMask boolean.
[MOD] LayerAttributeDrawer to now work with this new boolean.

## FIX
[FIX] NavMeshLayerAttributeDrawer to now give correct mask value if you skin n-amount of navmesharea names.

2023-06-15 13:26 UTC, GDGRhinox requested changes

2023-06-15 13:26 UTC, GDGRhinox commented on Assets/GUIUtils/Editor/Drawers/LayerAttributeDrawer.cs
> +using UnityEngine.AI;
Unnecessary using statements

2023-06-15 13:26 UTC, GDGRhinox commented on Assets/GUIUtils/Editor/Drawers/LayerAttributeDrawer.cs
> +                var result = _layerNameByIndex.FirstOrDefault(x => x.Key == property.intValue);
Why not use EditorGUI.layerfield here?

2023-06-17 14:53 UTC, GlennQuintyn commented on Assets/GUIUtils/Editor/Drawers/LayerAttributeDrawer.cs
> +                var result = _layerNameByIndex.FirstOrDefault(x => x.Key == property.intValue);
Good point, to be fully honest.
I did not know that existed.

2023-06-20 11:04 UTC, GDGRhinox approved these changes

2023-06-20 11:05 UTC, merged